apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no

resources:
    - ../../../base

labels:
    -   pairs:
            app.kubernetes.io/instance: fint-flyt-side-gateway_fintlabs_no
            fintlabs.no/org-id: fintlabs.no

patches:
    -   patch: |-
            -   op: replace
                path: "/spec/kafka/acls/0/topic"
                value: "fintlabs-no.flyt.*"
            -   op: replace
                path: "/spec/orgId"
                value: "fintlabs.no"
            -   op: replace
                path: "/spec/ingress/basePath"
                value: "/beta/fintlabs-no/api/side/instances"
            -   op: replace
                path: "/spec/probes/startup/path"
                value: "/beta/fintlabs-no/actuator/health"
            -   op: replace
                path: "/spec/probes/readiness/path"
                value: "/beta/fintlabs-no/actuator/health/readiness"
            -   op: replace
                path: "/spec/probes/liveness/path"
                value: "/beta/fintlabs-no/actuator/health/liveness"
            -   op: add
                path: "/spec/env/-"
                value:
                    name: novari.kafka.topic.org-id
                    value: "fintlabs-no"
            -   op: add
                path: "/spec/env/-"
                value:
                    name: server.servlet.context-path
                    value: "/beta/fintlabs-no"
            -   op: add
                path: "/spec/env/-"
                value:
                    name: novari.flyt.side.dispatch.enabled
                    value: "false"
        target:
            kind: Application
            name: fint-flyt-side-gateway
