fint:
    application-id: fint-flyt-side-gateway

logging:
    level:
        no.novari.cache.ehcache.FintEhCacheEventLogger: WARN
        no.novari.flyt.webresourceserver: DEBUG

server:
    error:
        include-message: always
    max-http-request-header-size: 40KB

spring:
    profiles:
        include:
        - flyt-file-client
        - flyt-kafka
        - flyt-logging
        - flyt-postgres
        - flyt-web-resource-server

    output:
        ansi:
            enabled: always
